runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:appmain

runtime_config:
  python_version: 2

#[START env]
env_variables:
    PUBSUB_TOPIC: AMRTopic
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: 1234abc
#[END env]
